export { default as authAPI } from './authAPI';
export { default as dashboardAPI } from './dashboardAPI';
export { default as credentialsAPI } from './credentialsAPI';
export { default as documentsAPI } from './documentsAPI';
export { default as inventoryAPI } from './inventoryAPI';
export { default as corporatePhoneAPI } from './corporatePhoneAPI';
export { default as ticketsAPI } from './ticketsAPI';
export { default as qualityTicketsAPI } from './qualityTicketsAPI';
export { default as purchaseRequestsAPI } from './purchaseRequestsAPI';
export { default as messagesAPI } from './messagesAPI';
export { default as qualityMessagesAPI } from './qualityMessagesAPI';
export { default as usersAPI } from './usersAPI';
export { default as rolesAPI } from './rolesAPI';
export { default as actaEntregaAPI } from './actaEntregaAPI';
export { default as tabletInventoryAPI } from './tabletInventoryAPI';
export { default as pdaInventoryAPI } from './pdaInventoryAPI';
export { getServerBaseURL } from './api';
